name: Main Workflow
on: 
  push:
    branches:
    - master
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Run hexo generate
      run: |
          npm i -g hexo-cli
          hexo generate
    - name: Run hexo deploy
      env:
        GH_DEPLOY_TOKEN: ${{secrets.GH_PAT}}
      run: |
        git config --global user.name 'wei.feng'
        git config --global user.email 'wei.feng'
        # sed -i "s/GH_PAT/${GH_PAT}/g" ./_config.yml
        hexo deploy

    # - name: Checkout
    #   uses: actions/checkout@v1
    # - name: Install
    #   run: npm install
    # - name: Clean
    #   uses: heowc/action-hexo@master
    #   with:
    #     args: clean
    # - name: Generate
    #   uses: heowc/action-hexo@master
    #   with:
    #     args: generate
    # - name: Deploy to Github Pages
    #   uses: maxheld83/ghpages@v0.2.1
    #   env:
    #     GH_PAT: ${{ secrets.HEXO_DEPLOY_PRI }}
        # BUILD_DIR: /github/workspace/public/
