name: Main Workflow
on: 
  push:
    branches:
    - master
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Configuration environment
      env:
        HEXO_DEPLOY_PRI: ${{secrets.HEXO_DEPLOY_PRI}}
      run: |
        mkdir -p ~/.ssh/
        echo "$HEXO_DEPLOY_PRI" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        eval `ssh-agent -s`
        ssh-add ~/.ssh/id_rsa
        git config --global user.name "wei.feng"
        git config --global user.email "wei.feng"

    - name: Install dependencies
      run: |
        npm i -g hexo-cli
        hexo generate

    - name: Deploy hexo
      run: |
        hexo deploy
